### ISSUE TITLE
Creating an OpenCollective

### ISSUE THREAD

**Issue by Jolg42** [opt-out-tools/opt-out#13]
See https://opencollective.com/

Would be great to get sponsors like we said at the meetup.

**Comment by MikeJohnPage** [comment]
Nice idea. Other options:
- https://www.bountysource.com/
- Add donate button to the README

**Comment by malteserteresa** [comment]
Hi Joël, I've sent you a link to slack from opt.out.tool@gmail.com, check your spam!

**Comment by Jolg42** [comment]
@malteserteresa It was indeed in my spam folder 😂 Thanks!

**Comment by malteserteresa** [comment]
I have applied for to be part of the Open Source Europe Collective as part of Open Collective. For this we need to have more people involved with the project, which will come once our website is ready
