### ISSUE TITLE
Travis CI or Git Lab  for Workflow

### ISSUE THREAD

**Issue by MikeJohnPage** [opt-out-tools/opt-out#23]
Add [Travis CI](https://travis-ci.com/):

- [Python docs](https://docs.travis-ci.com/user/languages/python/).

- [Beginner Guide](https://docs.travis-ci.com/user/for-beginners/).

**Comment by malteserteresa** [comment]
Homework on GitLab Vs GitHub:
- GitHub + Travis-CI == GitLab in terms of continuous deployment. No difference really.
- GitLab allows you to host private repos for free, GitHub only public
- GitLab enterprise features are cheaper than GitHub
- GitLab lets you set various different user levels for contributors to projects. GitHub is basically just read/write permissions.
-Github has way more users, 26 million Vs 100,000 at GitLab.

It doesn't really make much difference. Positives of sticking on GitHub is there is WAY more chance of getting community contribution as basically everyone has a GitHub account and not many people have a GitLab account. The other benefit is low cognitive overhead as you don't have to learn a new system. I can set up Travis CI if needs be. Benefit of switching is GitLab has better features and integrated CI (although using Travis there is no difference).

**Comment by Jolg42** [comment]
+1 for sticking to GitHub for visibility.

**Comment by MikeJohnPage** [comment]
I am with @Jolg42 on this one (even though GitLab seem like a much better platform all round!).

**Comment by malteserteresa** [comment]
Ok, lets Travis CI then :)
