### ISSUE TITLE
Decide which cloud hosting service to deploy to

### ISSUE THREAD

**Issue by malteserteresa** [opt-out-tools/opt-out#33]
**Objective**
Decide which cloud hosting service to use

**Description**
After struggling with AWS and it also costing a fair amount, we need to decide where to host the flask backend for our browser extension

**Skills** 
Flask, cloud hosting service, web dev

**Tools** 
Account or whichever cloud platform we decide on

**Detailed description**

**Comment by dkheyman** [comment]
I have written Flask apps on GCP with App Engine, so I could potentially help there. GCP offers a $300 free credit, could maybe be up your alley?
