### ISSUE TITLE
Linkrot on wiki

### ISSUE THREAD

**Issue by cmcaine** [opt-out-tools/opt-out#38]
Thanks for the wiki.

The APC link is broken on this page: https://github.com/opt-out-tools/opt-out/wiki/The-Problem

 New link is:

Permalink (according to their metadata, might not be real): https://www.apc.org/en/node/34685
Long link: https://www.apc.org/en/pubs/online-gender-based-violence-submission-association-progressive-communications-united-nations

**Comment by cmcaine** [comment]
Might be nice to add these papers to a public group on zotero.

This has the advantage of also stashing the pdfs of the papers online and also lets people import the whole lot into their reference manager easily.

**Comment by river-honer** [comment]
Did this get solve @cmcaine d?

**Comment by cmcaine** [comment]
I did make a zotero group that people could ask to join, but I don't know how many opt out people did do that.

The link on numbered item 10 on this page is still broken: https://github.com/opt-out-tools/opt-out/wiki/The-Problem and I do not have permission to change it.

**Comment by cmcaine** [comment]
I only briefly did academic research (a lit review) in this and I don't know what if any research other Opt Out team members are doing. If they are doing some, then it should maybe be on the website and the wiki just points to that?

**Comment by river-honer** [comment]
Can you please post a tl;dr

**Comment by cmcaine** [comment]
I could publish my coursework ;)

I think this issue should be closed by fixing the link in that one page (details above) or as wontfix.

**Comment by river-honer** [comment]
Lol yes thanks so much for clarifying. Let's get this fixed :)

**Comment by river-honer** [comment]
I fixed the link. Thanks and sorry for my repeated misunderstanding : )
