### ISSUE TITLE
Just a quick question on code frequency

### ISSUE THREAD

**Issue by eagleEggs** [opt-out-tools/opt-out#39]
How often are you commiting to this, as well as the API?

I'm looking at some code that is months old (with empty functions) and I'm not sure if you have some code waiting to commit. Also the API is django, but this is flask which I assume will be changed... Is there some organization method you could implement to keep track of your development? Perhaps the Projects functionality on Github: https://github.com/opt-out-tools/opt-out/projects?

This project is unique as it's new so I get that it's still getting organized and I'm sure you have your own development path right now :) Let me know as I'm interested in looking at this, and overall some clarity may help invite other contributors looking to assist- Thanks!

**Comment by malteserteresa** [comment]
Hi eagleEggs,

You're 100% right. It's just an interesting time for the browser extension
at the moment. We have a company who are using Opt Out as a pro-bono
project and they are working on it, hence why everything is out of date. I
havent kept up with updating issues and functionality on the github project
page as the work has been done elsewhere with them. Once we have our MVPs
from this company I shall update everything so we can open this baby up to
the open source community!

In the meantime, would you like to join our slack channel to keep in the
loop? This is where we are most active and all the interesting stuff is
happening.

Really glad you found us, and look forward to having you contribute once
we're more established.


Best,

T

**Comment by MikeJohnPage** [comment]
To expand further and answer some of your points:
- The project is migrating from Flask to Django
- We use a combination of Slack and Trello for organisation
- Check out our other GitHub channels, namely [find-out](https://github.com/opt-out-tools/find-out), which serves as a space to test ideas and experiments. We push code much more frequently there and you can find data sets, data wrangling scripts, EDA analysis and more (note there are several branches which will be merged at some point in the future).

**Comment by eagleEggs** [comment]
Ok cool. It would be nice to have some code to work off of and I hope that company provides some decent results soon. In the meantime I think this is my baby forked project now, I have some ideas at a slightly different scope that I will start putting together (Which perhaps this other company already is doing - Have no way of knowing). Maybe they can merge at a later point. Great idea - Keep it going!

Also if you could let me know the Slack / Trello info I'll gladly join. Thanks.

**Comment by malteserteresa** [comment]
We'll keep you posted!

https://join.slack.com/t/opt-out-workspace/shared_invite/enQtNzI3NTA0OTIzOTIxLWM1MGM5YzE1M2I1OGRhMDNiNjBhZjQ2MGM3YjdkMTg2MDQ3YzMzZmQyY2MyZGIwMjI0ZDBmOWExOGM3ZjgwOGY

:)

**Comment by eagleEggs** [comment]
Great, thanks :)
