### ISSUE TITLE
Linter not working

### ISSUE THREAD

**Issue by malteserteresa** [opt-out-tools/opt-out#54]
Running npm run linter in master produces this error

ESLint: 6.5.1.

ESLint couldn't find the config "strict/es5" to extend from. Please check that the name of the config is correct.

The config "strict/es5" was referenced from the config file in "/home/tcake/coding_projects/python/opt_out/browser_extension/extension/node_modules/check-error/package.json".

If you still have problems, please stop by https://gitter.im/eslint/eslint to chat with the team.

**Comment by nvhungTGO** [comment]
how you can fix this error, bro?

**Comment by gurdiga** [comment]
@nvhungTGO I have stubled upon this too and fixed it by ignoring the appropriate directories. :neckbeard: 

Check this out: https://eslint.org/docs/user-guide/configuring#ignoring-files-and-directories 🤓
