### ISSUE TITLE
Implement slider

### ISSUE THREAD

**Issue by malteserteresa** [opt-out-tools/opt-out#67]
## Goal

Make the slider in the extension more granular so the user can adjust the intensity of the filtering.
** This depends on https://github.com/opt-out-tools/public_api/issues/4 on the public API**

## Description

The slider in the browser extension is supposed to help the user adjust  how strict the filtering is.
Instead of just two steps, the slider should have 6 steps, from 0.5 to 1.

- [ ] Make extension accept predictions as decimal values (make sure booleans still work until backend change is deployed!)
- [ ] Create Design for slider with emojis (?)
- [ ] Implement prediction thresholds in the frontend based on slider value

## Acceptance Criteria:

- The slider can be set to 5 different values
- Adjusting the slider affects which tweets are filtered using the prediction value

**Comment by adrinjalali** [comment]
This is frontend, and I'm clueless when it comes to frontend. What is it that you want me to do @malteserteresa ?

**Comment by ribicn-softerrific** [comment]
I'll see to do work on frontend.

**Comment by ribicn-softerrific** [comment]
@malteserteresa If predicition returns 0. 5 for Tweet, is that tweet misogynistic or not??
We had 0 for 'not misogynistic` and 1 for 'misogynistic'.
I have added the slider values, and changed behavior for this issue. I just need to know for selector options(text invisible, text crossed, text removed), should i apply them for values 0.6 and higher, and treat 0.5 as i did 0 in older version, or should i add 0 beside 0.5-1.0 values??

**Comment by adrinjalali** [comment]
I'd say for any threshold `p`, any tweet with prediction value `>= p`
should be marked to be removed. The user should be able to set the value
`p` anything between 0 and 1, inclusive.

**Comment by river-honer** [comment]
We did this! But the backend wasn't ready :( We will consider all features more broadly and consider if this is still needed.
