### ISSUE TITLE
Serve model locally

### ISSUE THREAD

**Issue by Haimchen** [opt-out-tools/opt-out#72]
## Goal

Have a local instance of the model to make the predictions about tweets.

## Description

**Requires adjstment of the API: **

Instead of calling the /predict endpoint, the extension downloads the latest version of the model. Predictions are then made based on this local instance of the model.

First steps would include to find out how much data an extension can store and how big our model is.

**Comment by river-honer** [comment]
Closed: same as https://github.com/opt-out-tools/opt-out/issues/34
