### ISSUE TITLE
[WIP] GDPR around sending tweets

### ISSUE THREAD

**Issue by malteserteresa** [opt-out-tools/opt-out#90]
**Objective**

**Description**

**Skills**

**Tools**

**Time Estimation**

**Tasks**

- [ ] Step 1
- [ ] Step 2
- [ ] Step 3

**Comment by river-honer** [comment]
Understanding GDPR regulations

**Comment by river-honer** [comment]
@muaazsaleem If you have a moment to chime in :)

**Comment by river-honer** [comment]
Possible action: extend issue template to include GDPR section
