### ISSUE TITLE
API documentation

### ISSUE THREAD

**Issue by malteserteresa** [opt-out-tools/opt-out#92]
**Objective**

**Description**

**Skills**

**Tools**

**Time Estimation**

**Tasks**

- [ ] Step 1
- [ ] Step 2
- [ ] Step 3

**Comment by river-honer** [comment]
I think we already have some, need to investigate.

Not going to be achieved for this release (May 8th).

**Comment by river-honer** [comment]
We have backend API documentation that is hand written and possibly a bit outdated.

We decided that updating docs is a requirement of each PR, so documentation will progress. 

Let's close this issue, move forward with current plan and possibly automatic doc generation in the future.
